<%
var CONST;

CONST.exit = function(){
    console.exitFlag = true;
};

CONST.cd = function(to){
    return console.~cd(to);
};

CONST.exec = function(template){
    return console.~exec(template);
};

CONST.showLastException = function(){
    return console.~showLastException(console);
};

CONST.dir = 
CONST.ls  = function(path){
    console.~dir(path);
};


%>