<%
var CONST;

CONST.exit = () -> {console.exitFlag = true}

CONST.cd = to -> console.~cd(to)
CONST.exec = template -> console.~exec(template)
CONST.showLastException = () -> console.~showLastException(console)

CONST.dir = 
CONST.ls  = path -> {console.~dir(path)}


%>